### ISSUE TITLE
 Dynamically show or embed a word into the Drawingpad?

### ISSUE THREAD

**Issue by shilik** [bradmartin/nativescript-drawingpad#41]
@bradmartin 
I just wonder that if it is possible to dynamically show or embed a word into the pad?
An attribute like "text" that allows users to designate the background content of drawingpad. 
As a language teacher, I hope that a learner can hand-draw the word based on what is shown on the pad.
Thank you very much.

shilik
![drawing_trail](https://user-images.githubusercontent.com/1404868/41296156-e1aafffa-6e8e-11e8-9a2d-4548829e0855.png)

**Comment by bradmartin** [comment]
Not sure of all the functionality you're looking for. However, if you just want to indicate what the user should be drawing, you could very likely achieve it with something like the following:

```xml
<gridlayout rows="*" columns"*">
   <Image src="someImage" row="0" col="0" verticalAlignment="middle" horizontalAlignment="center"  />
   <DRAWINGPAD row="0" col="0" verticalAlignment="middle" horizontalAlignment="center"  />
</gridlayout>
```

The key being positioning both view on the same row/col in the grid, and then aligning them so that the 'drawingpad' is on "top" of the image that is initially rendered.
